alg: SAC
batch_size: 64
debug: false
env_id: Qube-100-v0
gamma: 0.99
git_hash: b8d03ab738e090b294520e6b3f62d0ef13fc66bd
git_url: git@github.com:neuralskeptic/smbrl.git
horizon: 200
initial_replay_size: 256
log_wandb: true
lr_actor: 0.0003
lr_alpha: 0.0003
lr_critic: 0.0003
m_ensemble: 2
max_replay_size: 500000
model_save_frequency: 1
n_critics_ensemble: 2
n_episodes_test: 10
n_epochs: 150
n_epochs_critic: 1
n_features_actor: 64
n_features_critic: 64
n_steps: 1000
plotting: false
preprocess_states: false
results_dir: ./logs/tmp/
seed: 7
tau: 0.005
use_cuda: false
verbose: false
wandb_entity: showmezeplozz
wandb_group: SAC
wandb_job_type: train
wandb_project: smbrl
warmup_transitions: 256
