alg: nlm
batch_size: 20000
dataset_file: models/2022_07_15__14_57_42/SAC_on_Qube-100-v0_100trajs_det.pkl.gz
debug: true
device: cuda
git_hash: 09706181a801ef8239aa22da587157260c2d7c97
git_url: git@github.com:neuralskeptic/smbrl.git
log_frequency: 0.01
lr: 0.001
max_replay_buffer_size: 10000
model_save_frequency: 0.1
n_epochs: 1500
n_epochs_between_rollouts: 10
n_epochs_rollout: 1
n_features: 128
n_initial_replay_episodes: 10
n_test_episodes: 10
plot_data: false
plotting: false
repo_dir: /home/daquinohilt/Documents/smbrl/scripts/..
results_dir: /home/daquinohilt/Documents/smbrl/scripts/../debug/logs/tmp/nlm_clone_SAC/0/2022_11_17__00_17_24
sac_agent_path: /home/daquinohilt/Documents/smbrl/scripts/../models/2022_07_15__14_57_42/agent_end.msh
sac_results_dir: /home/daquinohilt/Documents/smbrl/scripts/../models/2022_07_15__14_57_42
seed: 0
time_begin: 1668640644.570186
use_cuda: true
wandb_group: nlm_clone_SAC
